# Site settings
title: "Resume"
description: "Shubhi Gupta's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Shubhi Gupta"
resume_title:                   "Computer Science Undergraduate"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "shubhi.99gupta@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 9920481882"
resume_contact_address:         "3C-701, Whispering Palms, Lokhandwala Township"

resume_header_contact_info:     "3C-701, Whispering Palms, Lokhandwala Township • 9920481882 • shubhi.99gupta@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "Hi! I am a computer science undergraduate at SRM Institute of Science and Technology, studying image processing, statistics and neural networks, striving to develop fun and friendly solutions in automation. Aided with my hyperactive imagination, I often spend quality time in digital and 3D art and take quite the delight in conducing my version of the cities from the 31st century and sometimes even ramen bowls. I am personally attached to the quote - 'Curiosity killed the cat, but satisfaction brought it back.'"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/shubhi"
  resume_twitter_url:           "https://twitter.com/catthatcodes"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/shubhigupta99"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://shubhi.github.io"
  resume_url:                   "resume.pdf"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
